### PR TITLE
Create .gitignore

### PR DESCRIPTION
**Pull request by CK-Ward**

### CODE REVIEW

**Review by markjacksonfishing — APPROVED** [review]
I like what you did here

**Comment by ctsstc** [comment]
Are you sure we shouldn't just ignore everything?

**Comment by CK-Ward** [comment]
@ctsstc issa paradox, by ignoring nothing, do we ignore everything? 😳  and vice versa? 👀  ❗️ WHAAAA

**Comment by msander** [comment]
The paradox is, that you can consider .gitignore as part of the code. If this is accepted, code will have been written!

**Pull request closed without merging**
