### PR TITLE
added .gitignore

### PR DESCRIPTION
**Pull request by evanextreme**

### CODE REVIEW

**Comment by fabiomaia** [comment]
Hmm, maybe it should ignore `*` instead 🤔

**Comment by naeemkhan12** [comment]
and its been ignored :smiley:

**Comment by VPenkov** [comment]
> Hmm, maybe it should ignore `*` instead 🤔

That would mean adding something that would be interpreted by Git. One could argue that this is code, which conflicts with the purpose of this repository.
But then again, Dockerfile does have some content so this PR might be legit.

**Comment by 0something0** [comment]
>But then again, Dockerfile does have some content so this PR might be legit.

Just created a pull request to make Dockerfile blank

**Comment by VPenkov** [comment]
Amazing

**Comment by evanextreme** [comment]
bump

**Pull request closed without merging**
