### PR TITLE
Added support to multiple device and platforms

### PR DESCRIPTION
**Pull request by aftarfadilah**
This PR add supports to multiple devices and platform. Here is the full list of supported with this PR

- Smart Fridge #2830 
- Chromecast #2841 
- FireTV #2841 
- Amazon Alexa #1951
- Google Home #1998 
- Panzer IV
- Gatebox
- And many other that is too much to mention

### CODE REVIEW

**Comment by Dog2puppy** [comment]
I think this should be merged!

**Review by deepserket — APPROVED** [review]
Seems good, Ready to merge to master

**Comment by desktophero** [comment]
We're going to need a precedent for more `nocode` device targets to **not** put code on ... 

Prey, I mean, Pray with me:
Dear lord, they're going to figure out smaller, niche interfaces. We need to ship `nocode` to these widgets. 

Merge this, oh dear lord - if there is a [g|G]od. Please, set this as the path you see fit to make future interfaces flourish in your `nocode` liking as we see you. We are blessed to embark on a journey of new interfaces that can continue to indoctrinate the `nocode` approach we seek to apply to our everyday life. Albeit, CSV, XLS, or any data structure that we found on Hacker News.

Thanks be `nocode`'s name

And it may be so, with `nocode`'s blessing

**Comment by aftarfadilah** [comment]
[a|A]meen..

**Review by Ansaga — APPROVED** [review]

**Comment by aftarfadilah** [comment]
Closing this, it needs me 4 years to realize this PR has an issue which is no issue at all.

**Pull request closed without merging**
