### PR TITLE
Added Go support

### PR DESCRIPTION
**Pull request by saniales**
This PR adds support for Go (Golang) language

### CODE REVIEW

**Review by cjolivier01 — APPROVED** [review]

**Review by mishani0x0ef — APPROVED** [review]
Nice job, man.

**Review by arnavb — APPROVED** [review]

**Comment by krishnanandreddy** [comment]
Can't wait for the release.

**Comment by cityofships** [comment]
+1

**Review by the-codingninja — APPROVED** [review]
Thats awesome

**Review by freddygv — APPROVED** [review]

**Comment by derek1906** [comment]
+1

**Comment by eele94** [comment]
Looks promising!

**Review by avaschuk — APPROVED** [review]

**Pull request closed without merging**
