### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by mateothegreat**
To continue to do nothing otherwise this container would not keep doing nothing.

### CODE REVIEW

**Comment by sinback** [comment]
hi,

when I run this docker image, docker does something:
```
$ docker run 97792ab50ef2
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"tail\": executable file not found in $PATH": unknown.
ERRO[0001] error waiting for container: context canceled 
```
could you please update your PR so that docker does nothing again? I think this commit would break functionality for most of our users

**Comment by Bad-Science** [comment]
@sinback I think the problem may be with your usage. See: https://github.com/kelseyhightower/nocode#building-the-application

**Review by danyalaytekin — CHANGES_REQUESTED** [review]
```

```

**Comment by frankli0324** [comment]
@danyalaytekin OH GOD NO! YOUVE ADDED SOME CODE!

**Comment by Timtech4u** [comment]
> @sinback I think the problem may be with your usage. See: https://github.com/kelseyhightower/nocode#building-the-application

This fixes my issue, thanks!

**Pull request closed without merging**
