### PR TITLE
Add support for DogeScript (Not Code)

### PR DESCRIPTION
**Pull request by apppppppple**
This way no-code can be used by doge in doge-friendly language

### CODE REVIEW

**Comment by Variable-X** [comment]
[dogescript](dogescript.io)

**Comment by Variable-X** [comment]
#2956

**Comment by LusienGG** [comment]
You dont respect the project convention. Your PR has code!

**Comment by Variable-X** [comment]
No, it's an expression of doge thought!

**Review by linzhiq — APPROVED** [review]

**Pull request closed without merging**
