### PR TITLE
Vendoring dependencies of the nocode project

### PR DESCRIPTION
**Pull request by depado**
This PR adds a vendor directory.
This is obviously an empty directory since there are no dependencies.

### CODE REVIEW

**Comment by grahamlyons** [comment]
Probably best not to put anything into the container if we don't need to.

**Comment by Depado** [comment]
There's already a PR for a `.dockerignore` file, I prefer not to interfere with it right now.

**Comment by andreyors** [comment]
I would propose to have composer.json with name and description only)

**Comment by grahamlyons** [comment]
> No code is the best way to write secure and reliable applications.
No PHP, double so.

**Pull request closed without merging**
