### PR TITLE
Prevent people adding code by mistake

### PR DESCRIPTION
**Pull request by gepser**
I am trying to keep it simple (and readable) for every language, I know there are a lot of file extensions that could have code for this languages and of course, I am just adding the common ones. Feel free to add more languages.

I have read the [contributing guidelines](https://github.com/kelseyhightower/nocode/blob/master/CONTRIBUTING.md) before doing this pull request.

### CODE REVIEW

**Review by debnath — APPROVED** [review]

**Review by davidflanagan — APPROVED** [review]
Please add a .jsx extension to go along with .js.

Otherwise, looks good to me!

**Comment by gepser** [comment]
Done @davidflanagan 

And thanks!

**Comment by agilgur5** [comment]
Wouldn't it be better to implement the suggestion in #8 ? Though the proposal has run into some discussion relevant to #48 -- I think it's important to resolve these discussions and establish a new best practice, though no code should really have no opinions

**Review by poonai — APPROVED** [review]

**Comment by asciifaceman** [comment]
While I've 👍 the general idea, I disagree overall. One can have a file that implies code but does not contain code. The Dockerfile is a very good example. 

For example, if one wanted to contribute a deployment script, such as `deploy.sh` with no code, it still executes. 

Alternately, one can still contribute comments to sections of nocode without contributing code.

**Comment by agilgur5** [comment]
@asciifaceman I think these approaches are too opinionated for `nocode`. I've created #152 as a proposal that would have no opinions. Let me know your thoughts

**Review by d0nutptr — CHANGES_REQUESTED** [review]
I know you only are adding some common extensions but it seems that you're missing _these_ common extension :)

* Typescript (.ts, .tsx)
* Header files in c++ (.h)
* Coffeescript (.coffee)
* Rust (.rs)
* batch (.bat)
* shellscript (.sh)
* powershell (.ps1, .psd1, .psm1)
* postscript (.ps)

**Review by roylee0704 — APPROVED** [review]

**Comment by jiri-jagos** [comment]
When is this going to get to master please?

**Comment by roryai** [comment]
Suggest setting contents of .gitignore to ```*.*``` to prevent unforeseen additions.

**Review by roryai — CHANGES_REQUESTED** [review]
Suggest setting contents of .gitignore to ```*.*``` to prevent unforeseen additions.

**Comment by pablocarreraest** [comment]
hi @roryai, it can have conflict with the documentation files

**Comment by WarFox** [comment]
I would suggest this method https://github.com/kelseyhightower/nocode/pull/209

**Review by marcosalles — CHANGES_REQUESTED** [review]
Maybe you could replace the first 31ish lines by `*`

edit: PR https://github.com/kelseyhightower/nocode/pull/209 seems like the way to go on this case, as @WarFox suggested

**Comment by gepser** [comment]
Guys, I don't want to take the approach to ignore all the files because we may miss by mistake some documentation files, like Markdown, maybe images. That's why we never do this in any `gitignore` file.

@d0nutptr I just added your suggestions.

**Review by AaronValor — APPROVED** [review]
*.*?

**Review by dlhandsome — APPROVED** [review]

**Pull request closed without merging**
