### PR TITLE
Create requirements.txt

### PR DESCRIPTION
**Pull request by m-schwarzinger**
I added some important modules

### CODE REVIEW

**Comment by ghost** [comment]
the interpreter throws the following error when running the file: `CIAL`, please run `rm requirements.txt && touch requirements.txt` to fix the errors

**Comment by m-schwarzinger** [comment]
I changed the package to the very important "nothing" package in the version 0.0.3

**Comment by ghost** [comment]
still contains bytes

**Comment by m-schwarzinger** [comment]
empty files can't be commited

**Review by neo-mashiro — APPROVED** [review]

**Pull request closed without merging**
