### PR TITLE
‮­ 

### PR DESCRIPTION
**Pull request by ikapelyukhin**

### CODE REVIEW

**Comment by ikapelyukhin** [comment]
My greatest contribution to open source:
image

:neckbeard:

**Comment by Wqrld** [comment]
how did you do that almost unclickable title

**Comment by ikapelyukhin** [comment]
@Wqrld I've copied it from #1532 :joy:
It's a `&#8238;&shy;` sequence -- left-to-right override character and a soft-hyphen.

**Comment by kalabiyau** [comment]
Awesome!!! Way to go!

**Comment by achillesrasquinha** [comment]
Let's merge this!

Oh wait...

**Comment by merzak7** [comment]
&#8238;&shy;

**Comment by ikapelyukhin** [comment]
Closing the PR so that it doesn't show up on the list of my PRs anymore :D

**Pull request closed without merging**
