### PR TITLE
add a hello world example

### PR DESCRIPTION
**Pull request by thrzl**
adds a simple hello world example

### CODE REVIEW

**Comment by descovi** [comment]
Maybe you add some complexity with the creation of a file 🤔

**Comment by jasonnoble** [comment]
If we follow the [Style Guide](https://github.com/kelseyhightower/nocode/blob/master/STYLE.md) is this PR more of a `LGTM` or a `CIAL` situation?

Does the Style Guide need updating to handle adding blank lines?

**Comment by thrzl** [comment]
Considering the style guide, the filesize should be zero. Even adding nothing (`​`) will raise the size to approx 4 bytes, failing the `du ` check. I have checked this code for performance issues and checked that this is style-conforming. If you do find any issues, do tell me.

**Comment by thrzl** [comment]
> Maybe you add some complexity with the creation of a file 🤔

I could always make the filename:
`‎`
or `‎.no`

**Review by vadimfilimonov — APPROVED** [review]

**Review by domi-btnr — APPROVED** [review]

**Pull request closed without merging**
