### PR TITLE
add nothing

### PR DESCRIPTION
**Pull request by vadimfilimonov**
There is no diff.

### CODE REVIEW

**Review by Rijak0 — APPROVED** [review]

**Comment by rosesonfire** [comment]
Can you please add some description? It's a bit daunting to follow the changes without knowing what should be expected in the diff.

**Comment by vadimfilimonov** [comment]
> Can you please add some description? It's a bit daunting to follow the changes without knowing what should be expected in the diff.

There is no diff.

**Comment by rosesonfire** [comment]
> There is no diff.

Yep, that can be a good description. Would save so much time.

**Review by BillGR17 — APPROVED** [review]

**Comment by domini7** [comment]
###

**Review by alisafili — APPROVED** [review]

**Review by BogdanovBogdan — APPROVED** [review]

**Comment by quenbyako** [comment]
@VadimFilimonov found tiny bug:

If you type:

```

```

than you see pretty strange error message:

```

```

I don't know how to fix it, but if i change [this line](https://github.com/VadimFilimonov/nocode/commit/e5b58352eaf36fc4f137f37caff4e0727ee84d1c/#L0) from ` ` to ` `, then this error message passes, and a unicorn teleports to your room for some reason. At least it's way better than nothing.

<details>
  <summary></summary>
No seriously, this fucking unicorn lay down on my bed and poops with cotton candy, man. Don't mind anything, but could please you write unit tests for next time <b>before</b> creating a PR? My whole room is sticky from unicorn poop. and pinky. Someone call the cleaners
</details>

**Comment by vadimfilimonov** [comment]
@quenbyako 

> At least it's way better than nothing.

There is nothing better than nothing.

**Review by Cube9999 — APPROVED** [review]

**Review by Misaka13514 — APPROVED** [review]

**Review by quenbyako — APPROVED** [review]
LGTM

**Review by Coac — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by vitalymak** [comment]
Kind of my favourite PR!

**Review by JeremyRms — CHANGES_REQUESTED** [review]
You forgot the linting

**Comment by ghost** [comment]
linter passes all tests, CI also likes this pr

**Review by GeorgyBoyko — APPROVED** [review]

**Comment by girisagar46** [comment]
CIAL

**Pull request closed without merging**
