### PR TITLE
Sharing the best practice to the world!

### PR DESCRIPTION
**Pull request by cheng-kang**
Added `/docs` folder, translations page, and `Chinese` version.

Set up GitHub pages for this repo, and make it more sharable!

<p align="center">
  
  
  
</p>

### CODE REVIEW

**Comment by cheng-kang** [comment]
@kelseyhightower Please review 😃

**Review by denisnikulin — APPROVED** [review]

**Comment by ascensionra** [comment]
Disagree. Github pages utilize md code and themes, violating the design principles of the framework. Implement this pull request would break the code.

**Comment by cheng-kang** [comment]
@ascensionra according to your understanding of the principles, this repo should be deleted then.

**Comment by cheng-kang** [comment]
Thank you for your review @denisnikulin 🤓

**Pull request closed without merging**
