### PR TITLE
Lint

### PR DESCRIPTION
**Pull request by tedmiston**
Is it really no code if it doesn't pass markdownlint???

_Really just trying to make that contribs page with no effort._

### CODE REVIEW

**Comment by ArturLange** [comment]
`+0 −6` - looking good 👍

**Comment by klamping** [comment]
Any chance this is going to get merged in and released soon? I need it for a work project.

**Comment by tedmiston** [comment]
@klamping I think the maintainer has gone MIA.  Perhaps it is time we start our own distribution?

**Comment by klamping** [comment]
@tedmiston yeah, it's been about 3 days, so definitely an abandoned project. I'll fork this repo and commit this single change, then not make or accept a single change after that. Seems like the right thing to do.

**Pull request closed without merging**
