### PR TITLE
Fix nothing

### PR DESCRIPTION
**Pull request by exdeejay**

### CODE REVIEW

**Comment by anthdm** [comment]
Any ETA on when this PR will hit master?

**Comment by archibold** [comment]
could you merge it to master? It is blocker for my urgent tasks

**Comment by anthdm** [comment]
@archibold I just noticed an ambiguous variable name.

```
// see below
```

**Comment by arnauguadall** [comment]
// see above

**Comment by anthdm** [comment]
> // see above

```
```

**Comment by trthhrtz** [comment]
Approved

**Review by vinc — CHANGES_REQUESTED** [review]
Change nothing

**Comment by oferze** [comment]
This LGTM:
<code>
</code>

**Comment by gauravano** [comment]
>

**Review by Daniel15 — APPROVED** [review]

**Comment by duellsy** [comment]
Any updates?

**Comment by anthdm** [comment]
@albinekb Business shut down, I'm so sorry...

**Review by mpyw — APPROVED** [review]

**Review by anisjonischkeit — APPROVED** [review]

**Review by Zethson — APPROVED** [review]

**Review by ArturFormella — APPROVED** [review]

**Review by jaredallard — APPROVED** [review]

**Review by crewsycrews — APPROVED** [review]

**Review by hgross — APPROVED** [review]

**Comment by fritx** [comment]
Any progress?

**Review by Ten0 — APPROVED** [review]
This definitely removes most of the boilerplate in the no-code based apps. A must have! I'll be using the fork in the meantime :)

**Comment by anthdm** [comment]
I suggest to re-open this issue due to:

`nothing`

**Pull request closed without merging**
