### PR TITLE
Add NoCode++ main file

### PR DESCRIPTION
**Pull request by esblygiad**
Add NoCode++ compiler file. Supports NoCode and NoCode#

### CODE REVIEW

**Comment by MinekPo1** [comment]
Does nocode need dialects?

Dialects only add unnecessary syntax, which in turn means unnecessary code is written.

**Comment by esblygiad** [comment]
> Does nocode need dialects?
> 
> Dialects only add unnecessary syntax, which in turn means unnecessary code is written.

It's simply for choice of syntax, it all compiles to nocode and does the same thing, for example:

One plus one

Nocode:
Nocodepp:
Nocode#:

**Comment by MinekPo1** [comment]
This is against all that the nocode project stands for.

nocode stands for simplicity. Embracing dialects like this will only add
confusion and put more stress on developers.

**Comment by esblygiad** [comment]
Some users don't like certain paradigms. Dialects would allow users to avoid certain paradigms while embracing others. Sticking to one standard paradigm will be more frustrating that having multiple.

**Comment by MinekPo1** [comment]
The NoCode project, again, stands for simplicity and ease of use. Adding dialects will mean users might mistake one dialect for another when looking at scraps of code.

Regardless, extra paradigms stand against this core idea as well. The simplicity of NoCode can suffer if you add such syntactic shuggar to it.

**Comment by esblygiad** [comment]
Isn't NoCode for simplicity? Why make your users suffer?

**Comment by MinekPo1** [comment]
Exactly. I glad you see my point.

**Comment by esblygiad** [comment]
You clearly don't

**Pull request closed without merging**
