### PR TITLE
Create Install instructions

### PR DESCRIPTION
**Pull request by Nyameliaaaa**

### CODE REVIEW

**Review by Art4 — APPROVED** [review]
LGTM!

**Review by w3bdesign — APPROVED** [review]
No code, no installation

**Review by panzerstadt — APPROVED** [review]
LGTM

**Comment by Nyameliaaaa** [comment]
@kelseyhightower When Will this be merged in?

**Comment by mmphego** [comment]
Ship it.

**Comment by Nyameliaaaa** [comment]
:shipit: :github: :octocat:

**Comment by Nyameliaaaa** [comment]
:shipit:

**Review by mmphego — APPROVED** [review]

**Comment by Nyameliaaaa** [comment]
:shipit:

**Pull request closed without merging**
