### PR TITLE
​

### PR DESCRIPTION
**Pull request by dapirian**
​

### CODE REVIEW

**Comment by VixieTSQ** [comment]
LGTM!

**Comment by shiralizadeh** [comment]
Well done!

**Comment by Wybxc** [comment]
<br>

**Review by Xunzhuo — APPROVED** [review]
LGTM!

**Comment by vincentinttsh** [comment]
LGTM

**Review by nirs — APPROVED** [review]

**Comment by purrseus** [comment]
LGTM!

**Comment by Khongkong** [comment]
Brilliant!

**Comment by bougwal** [comment]
LGTM!

**Review by KovalenkoVolodymyr — APPROVED** [review]

**Review by blyxyas — APPROVED** [review]
>

**Comment by CleoMenezesJr** [comment]
MTGT

**Comment by chermed** [comment]
```
```

**Comment by iamroylim** [comment]
well done

**Review by Morilli — APPROVED** [review]

**Comment by yusufmalikul** [comment]
LGTM

**Comment by ProfLander** [comment]
SMH at all of these non-contributors posting LGTM.

That being said, looks good to me.

**Review by domi-btnr — APPROVED** [review]

**Review by Shisuki — APPROVED** [review]

**Review by jazzg62 — APPROVED** [review]

**Comment by jazzg62** [comment]
&nbsp;

**Review by igorcaavalcante — APPROVED** [review]

**Review by mp-singh — APPROVED** [review]
Teach me the way sensei!

**Pull request closed without merging**
