### PR TITLE
add more nocode

### PR DESCRIPTION
**Pull request by sudoforge**
this commit adds some additional nocode to bring in a more advanced
feature set, including the following:

### CODE REVIEW

**Comment by CAMOBAP** [comment]
thanks for opening this, I really miss it(

**Review by vadimfilimonov — APPROVED** [review]

**Review by 132ikl — APPROVED** [review]

**Review by kevkevinpal — APPROVED** [review]

**Review by fjkfwz — APPROVED** [review]

**Review by wangy265 — APPROVED** [review]

**Comment by KSH-code** [comment]
how to add no changes commit?

**Review by Starrah — APPROVED** [review]

**Review by jlwollinger-zz — APPROVED** [review]

**Review by ingoaf — APPROVED** [review]

**Review by vadimfilimonov — APPROVED** [review]

**Review by Pupyrinth — APPROVED** [review]

**Review by thrzl — APPROVED** [review]

**Review by brian-petersen — APPROVED** [review]

**Review by adeds — APPROVED** [review]

**Review by scuilla — APPROVED** [review]

**Comment by sudoforge** [comment]
> how to add no changes commit?

@KSH-code sorry I missed this, I've turned notifications off for this thread.

```
$ man git-commit

      ...
       --allow-empty
           Usually recording a commit that has the exact same tree as its sole parent commit is a mistake, and the command prevents you from making such a commit. This option bypasses the safety, and is primarily for use by
           foreign SCM interface scripts.
      ...
```

**Review by Salmandabbakuti — APPROVED** [review]
LGTM ALL

**Pull request closed without merging**
