### PR TITLE
Create Makefile

### PR DESCRIPTION
**Pull request by djmetzle**
make nocode

### CODE REVIEW

**Comment by MarounMaroun** [comment]
Looks good to me.

**Review by archae0pteryx — COMMENTED** [review]
I can see the argument that this could be 'code'

**Comment by lzzy12** [comment]
Please use CMake instead for support for all compilers like VS

**Comment by eliemugenzi** [comment]
This looks good to me

**Review by eliemugenzi — APPROVED** [review]

**Pull request closed without merging**
